ALTER TABLE "Company"
  ADD COLUMN IF NOT EXISTS "eHouwiyaStatus" TEXT NOT NULL DEFAULT 'NOT_STARTED',
  ADD COLUMN IF NOT EXISTS "eHouwiyaIdentifier" TEXT,
  ADD COLUMN IF NOT EXISTS "eHouwiyaVerifiedAt" TIMESTAMP(3);
