ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "legalStatus" TEXT NOT NULL DEFAULT 'draft';
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "paymentStatus" TEXT NOT NULL DEFAULT 'unpaid';
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "ttnReference" TEXT;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "ttnProofPath" TEXT;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "teifXmlPath" TEXT;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "teifXmlHash" TEXT;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "teifGeneratedAt" TIMESTAMP(3);
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "teifVersion" TEXT;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "signedXmlPath" TEXT;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "signatureStatus" TEXT;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "signatureTimestamp" TIMESTAMP(3);
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "signedByUserId" TEXT;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "certificateIdentifier" TEXT;

ALTER TABLE "UserActivityLog" ADD COLUMN IF NOT EXISTS "ipAddress" TEXT;
ALTER TABLE "UserActivityLog" ADD COLUMN IF NOT EXISTS "userAgent" TEXT;
ALTER TABLE "UserActivityLog" ADD COLUMN IF NOT EXISTS "errorMessage" TEXT;
